[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
SurrogatedDistanceModels = "0e04eddd-96ac-454e-8372-d12cc190ad6e"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
CSV = "0.10"
DataFrames = "^1"
FileIO = "1.16"
Glob = "^1"
HDF5 = "0.17"
JLD2 = "0.4"
SimilaritySearch = "0.11.8"
SurrogatedDistanceModels = "0.1"
UnicodePlots = "3.6"
